batch_size: 1024
checkpoint: null
ensemble_method: averaging
ensemble_size: 4
epochs: 1000
hidden_bitwidth: 3
hidden_fanin: 4
hidden_layers:
- 32
- 64
- 192
- 192
- 16
input_bitwidth: 4
input_fanin: 3
learning_rate: 0.001
output_bitwidth: 7
output_fanin: 5
post_transform_output: false
quantize_avg: false
seed: 16
weight_decay: 0.001
