activation_bitwidth:
- 2
- 2
- 3
batch_size: 512
ensemble_hp:
  fixed_sparsity_mask: false
ensemble_method: voting
ensemble_size: 8
epochs: 200
hidden_layer:
- 128
- 128
- 128
input_bitwidth: 5
input_fanin: 2
lr: 0.0004919504148576049
neuron_fanin:
- 5
- 2
- 2
output_bitwidth: 2
seed: 1665510883
warm_restart_freq: 73
wd: 0.001107296416119917
