activation_bitwidth:
- 2
- 2
- 3
batch_size: 512
ensemble_hp:
  fixed_sparsity_mask: false
  independent: false
ensemble_method: adaboost
ensemble_size: 32
epochs: 200
finetune_epochs: 10
hidden_layer:
- 128
- 128
- 128
input_bitwidth: 5
input_fanin: 2
lr: 0.001
neuron_fanin:
- 5
- 2
- 2
output_bitwidth: 2
seed: 2
warm_restart_freq: 50
wd: 0.01
