activation_bitwidth:
  max: 6
  min: 2
hidden_layer:
  max: 5
  min: 1
input_bitwidth:
  max: 6
  min: 4
input_fanin:
  max: 3
  min: 2
lr:
  max: 0.1
  min: 1.0e-05
neuron_fanin:
  max: 6
  min: 1
num_features:
  max: 512
  min: 16
num_seeds_per_trial: 3
num_trials: 5
output_bitwidth:
  max: 6
  min: 2
search_learning_params: true
search_model_arch: true
seed: 1
warm_restart_freq:
  max: 100
  min: 10
wd:
  max: 0.1
  min: 1.0e-05
