activation_bitwidth:
- 3
- 3
- 4
batch_size: 512
ensemble_hp:
  fixed_sparsity_mask: true
  same_input_scale: true
  same_output_scale: true
  shared_input_bitwidth: 6
  shared_input_layer: false
  shared_output_layer: false
ensemble_method: voting
ensemble_size: 8
epochs: 200
hidden_layer:
- 512
- 512
- 64
input_bitwidth: 6
input_fanin: 2
lr: 0.001
neuron_fanin:
- 4
- 5
- 3
output_bitwidth: 5
seed: 2
warm_restart_freq: 100
wd: 0.0
