activation_bitwidth:
- 2
- 6
batch_size: 512
epochs: 200
hidden_layer:
- 256
- 256
input_bitwidth: 5
input_fanin: 3
lr: 0.0001
neuron_fanin:
- 5
- 2
output_bitwidth: 6
seed: 2036987025
warm_restart_freq: 100
wd: 0.01
