batch_size: 1024
checkpoint: null
ensemble_method: averaging
ensemble_size: 8
epochs: 1000
hidden_bitwidth: 2
hidden_fanin: 3
hidden_layers:
- 64
- 32
- 32
- 32
input_bitwidth: 2
input_fanin: 3
input_length: 16
learning_rate: 0.001
output_bitwidth: 2
output_fanin: 3
output_length: 5
post_transform_output: true
quantize_avg: false
same_input_scale: true
same_output_scale: false
seed: 2
weight_decay: 0.001
