activation_bitwidth:
- 2
- 2
- 3
- 4
- 3
- 4
batch_size: 512
ensemble_hp:
  cycle: 4
  lr1: 0.0001
  lr2: 1.0e-06
ensemble_method: fge
ensemble_size: 16
epochs: 200
finetune_epochs: 10
hidden_layer:
- 128
- 256
- 256
- 256
- 256
- 128
input_bitwidth: 4
input_fanin: 2
lr: 0.0001
neuron_fanin:
- 4
- 6
- 4
- 2
- 3
- 2
output_bitwidth: 5
seed: 1
warm_restart_freq: 100
wd: 0.001
