batch_size: 1024
checkpoint: null
ensemble_method: averaging
ensemble_size: 2
epochs: 1000
hidden_bitwidth: 2
hidden_fanin: 3
hidden_layers:
- 64
- 32
- 32
- 32
input_bitwidth: 2
input_fanin: 3
input_post_trans_sbs: false
learning_rate: 0.001
output_bitwidth: 2
output_fanin: 3
post_transform_output: false
quantize_avg: false
same_input_scale: false
same_output_scale: false
same_output_scale_sum: true
seed: 2
shared_input_bitwidth: 6
shared_input_layer: true
shared_input_quant: true
uniform_connectivity: false
uniform_input_connectivity: false
weight_decay: 0.001
