# Fixed params
activation_bitwidth:
- 3
- 3
- 4
batch_size: 512
ensemble_method: adaboost
ensemble_hp:
  independent: True
ensemble_size: 32
epochs: 200
hidden_layer:
- 512
- 512
- 64
input_bitwidth: 6
input_fanin: 2
lr: 0.001
neuron_fanin:
- 4
- 5
- 3
output_bitwidth: 5
warm_restart_freq: 100
wd: 0.01

# Params to grid search
grid_search_params:
  seed:
  - 432384445
  - 1
  - 2