# Fixed params
activation_bitwidth:
- 2
- 2
- 2
- 6
batch_size: 512
ensemble_method: snapshot
epochs: 1600
finetune_epochs: 10
hidden_layer:
- 128
- 256
- 128
- 128
input_bitwidth: 4
input_fanin: 2
lr: 0.001
neuron_fanin:
- 6
- 5
- 4
- 2
output_bitwidth: 6
warm_restart_freq: 100
wd: 1.0e-05

# Params to grid search
grid_search_params:
  ensemble_size:
  # - 2 # 200 epochs
  # - 4 # 400
  # - 8 # 800
  # - 16 # 800 epochs
  - 32 # 1600 epochs
  seed: 
  - 963241121
  - 1
  - 2

