# Fixed params
activation_bitwidth:
- 3
- 3
- 4
batch_size: 512
ensemble_method: snapshot
epochs: 1600
finetune_epochs: 10
hidden_layer:
- 512
- 512
- 64
input_bitwidth: 6
input_fanin: 2
lr: 0.001
neuron_fanin:
- 4
- 5
- 3
output_bitwidth: 5
warm_restart_freq: 100
wd: 0.01

# Params to grid search
grid_search_params:
  ensemble_size:
  # - 2 # 200 epochs
  # - 4 # 400
  # - 8 # 800
  # - 16 # 800 epochs
  - 32 # 1600 epochs
  seed: 
  - 432384445
  - 1
  - 2