# Fixed params
activation_bitwidth:
- 3
- 4
batch_size: 512
epochs: 200
hidden_layer:
- 64
- 128
input_bitwidth: 5
input_fanin: 2
neuron_fanin:
- 3
- 3
output_bitwidth: 4
seed: 1583736550

# Params to grid search
grid_search_params:
  lr: 
  - 0.005
  - 0.001
  warm_restart_freq: 
  - 50
  - 100
  wd: 
  - 0.00001
  - 0.0001
  - 0.001
