apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ensemblelut
  namespace: xdr
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
