activation_bitwidth:
- 5
- 5
- 5
batch_size: 512
epochs: 100
hidden_layer:
- 128
- 128
- 512
input_bitwidth: 6
input_fanin: 2
lr: 0.001
neuron_fanin:
- 3
- 3
- 2
output_bitwidth: 4
seed: 897072296
warm_restart_freq: 25
wd: 0.0001
