activation_bitwidth:
- 2
- 2
- 2
- 6
batch_size: 512
ensemble_hp:
  fixed_sparsity_mask: false
  same_input_scale: true
  same_output_scale: true
  shared_input_bitwidth: 6
  shared_input_layer: false
  shared_output_layer: false
ensemble_method: voting
ensemble_size: 8
epochs: 200
hidden_layer:
- 128
- 256
- 128
- 128
input_bitwidth: 4
input_fanin: 2
lr: 0.001
neuron_fanin:
- 6
- 5
- 4
- 2
output_bitwidth: 6
seed: 1
warm_restart_freq: 100
wd: 0
