activation_bitwidth:
- 5
- 4
- 4
batch_size: 1024
epochs: 100
hidden_layer:
- 128
- 128
- 64
input_bitwidth: 6
input_fanin: 2
lr: 0.01
neuron_fanin:
- 3
- 2
- 4
output_bitwidth: 4
seed: 479243557
warm_restart_freq: 50
wd: 0.01
