activation_bitwidth:
- 2
- 2
- 3
batch_size: 512
epochs: 200
hidden_layer:
- 128
- 128
- 128
input_bitwidth: 5
input_fanin: 2
lr: 0.0005
neuron_fanin:
- 5
- 2
- 2
output_bitwidth: 2
seed: 1665510883
warm_restart_freq: 100
wd: 0.01
